# Port to run on
server:
  port: ${port:8080}

# Our log file path and name
logging:
  file: logs/erc20-rest-service.log

# Endpoint of an Ethereum or Quorum node we wish to use.
# To use IPC simply provide a file path to the socket, such as /path/to/geth.ipc
nodeEndpoint: http://localhost:8545

# The Ethereum or Quorum address we wish to use when transacting.
# Note - this address must be already unlocked in the client
# Local testing with Ganache uses nemonic - rubber taste draw shoulder august sun top trade nose oil absent talk
fromAddress: "0x6536dEE67952444Ce06ae7Efe573C9a3d7041162"